# Default PPO training configuration
# @package _global_

# Policy loading configuration
load_actor: [false, false]
load_critic: [false, false]

# Training configuration
train_actor: true
train_critic: true
val_freq: 50
total_updates: 1000000
steps_per_update: 512
lr: 3.0e-4
self_play: true

# Parallel rollout configuration
n_rollout_workers: 32
n_rollouts_per_worker: 128

# WandB configuration
run_name: null

